apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # wave 0 install servicemesh first
  - servicemesh-operator/subscription-servicemesh.yaml
  # wave 1 install serverless second
  - serverless-operator/namespace-serverless.yaml
  - serverless-operator/operator-group-serverless.yaml
  - serverless-operator/subscription-serverless.yaml
  # wave 2 define namespace
  - rhoai-operator/namespace.yaml
  - rbac/cluster-role-binding-dsc.yaml
  - rbac/argocd-istio-routes-rbac.yaml
  # wave 4 install rhoai operator
  - rhoai-operator/operator-group.yaml
  - rhoai-operator/subscription-rhoai.yaml
  # wave 5 create data science cluster (creates KServe CRDs)
  - rhoai-operator/data-science-cluster.yaml
