apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: module-lightspeed
  namespace: openshift-gitops
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - name: web-terminal-operator
            path: module-lightspeed/install-web-terminal
          - name: pipelines-operator
            path: module-lightspeed/install-pipelines
  template:
    metadata:
      name: "{{ .name }}"
      namespace: openshift-gitops
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/red-hat-data-services/genaidemo25-gitops.git
        targetRevision: HEAD
        path: "{{ .path }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: openshift-operators
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
          - RespectIgnoreDifferences=true
      revisionHistoryLimit: 3
