apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workshop-server-pvc
  labels:
    app: workshop-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3-csi
