apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: openshift-gitops
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  rbac:
    defaultPolicy: ""
    scopes: "[groups,email]"
    policy: |
      g, system:cluster-admins, role:admin
      g, cluster-admins, role:admin
      g, hackathon, role:admin
