apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: {{ .Values.runtime.name }}
  namespace: {{ .Values.namespace.name }}
  annotations:
    opendatahub.io/accelerator-name: {{ .Values.runtime.annotations.acceleratorName }}
    opendatahub.io/apiProtocol: {{ .Values.runtime.annotations.apiProtocol }}
    opendatahub.io/hardware-profile-name: {{ .Values.runtime.annotations.hardwareProfileName | quote }}
    opendatahub.io/recommended-accelerators: {{ .Values.runtime.annotations.recommendedAccelerators | quote }}
    opendatahub.io/runtime-version: {{ .Values.runtime.annotations.runtimeVersion }}
    opendatahub.io/serving-runtime-scope: {{ .Values.runtime.annotations.servingRuntimeScope }}
    opendatahub.io/template-display-name: {{ .Values.runtime.annotations.templateDisplayName }}
    opendatahub.io/template-name: {{ .Values.runtime.annotations.templateName }}
    openshift.io/display-name: {{ .Values.runtime.displayName }}
  labels:
    opendatahub.io/dashboard: "true"
spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
  containers:
    - command:
        - sh
        - -c
      args:
        - |
          {{- with .Values.runtime.preStartScript }}
          {{ . | trim | replace "\n" "\n          " }}
          {{- end }}
          exec python3 -m vllm.entrypoints.openai.api_server --port=8080 --model=/mnt/models{{- if .Values.model.file }}/{{ .Values.model.file }}{{- end }} "--served-model-name={{`{{.Name}}`}}"{{- range .Values.runtime.extraArgs }} {{ . }}{{- end }}
      env:
        - name: HF_HOME
          value: /tmp/hf_home
        - name: HF_HUB_OFFLINE
          value: "1"
      {{- with .Values.runtime.extraEnv }}
      {{- range $k, $v := . }}
        - name: {{ $k }}
          value: {{ $v | quote }}
      {{- end }}
      {{- end }}
      image: {{ .Values.runtime.image }}
      name: kserve-container
      ports:
        - containerPort: 8080
          protocol: TCP
      volumeMounts:
        - mountPath: /dev/shm
          name: shm
      {{- with .Values.runtime.extraVolumeMounts }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: {{ .Values.model.format }}
  volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 2Gi
      name: shm
  {{- with .Values.runtime.extraVolumes }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
